[build]
builder = "dockerfile"
dockerfilePath = "deployments/docker/Dockerfile"

[deploy]
startCommand = "./api"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"